### ISSUE TITLE
Model is not finalizing

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE_Processing#111]
Hello @BSchilperoort 
I noticed that the model is not finalized with an error message if the model is running for longer periods (e.g. 20 days). I did several tests with different sites but always same problem. I actually can't figure out where is the problem, so would appreciate your help. I attached the model here in case you could test from your side.

[NL-Loo_2024-11-13-1159.zip](https://github.com/user-attachments/files/17735617/NL-Loo_2024-11-13-1159.zip)

![Screenshot 2024-11-13 170345](https://github.com/user-attachments/assets/452cb55a-4e51-47c7-b910-e8ee2a933806)

**Comment by BSchilperoort** [comment]
Maybe the model is encountering an error during finalization. Maybe something is going wrong trying to write data to file.

I am not sure if errors are written to a log file, this would be a good improvement for stemmus_scope as it'll make it easier to debug these issues.
e.g. https://nl.mathworks.com/help/matlab/ref/diary.html

**Comment by MostafaGomaa93** [comment]
I run the model through Matlab (without Pystemmusscope) and it runs to the end successfully

**Comment by SarahAlidoost** [comment]
> I run the model through Matlab (without Pystemmusscope) and it runs to the end successfully

Just to clarify, did you run the model via matlab and bmi interface? the `finalize` is a bmi function and [this block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/b9b4f8231955589d3394ec5148950467eeaa4ec3/src/STEMMUS_SCOPE.m#L814-L827) is where the function is used.

Another point, please check if your pystemmusscope installation is based on the main branch in this repo since the newest changes have not been released yet.

**Comment by MostafaGomaa93** [comment]
> 
> Just to clarify, did you run the model via matlab and bmi interface? the `finalize` is a bmi function and [this block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/b9b4f8231955589d3394ec5148950467eeaa4ec3/src/STEMMUS_SCOPE.m#L814-L827) is where the function is used.

If I run without BMI, the model runs successfully. If I run through BMI, the final step `model.finalize()` gave an error (error message showed above). Through BMI, the model actually runs to the end, but not all the csv files are generated and the binary files are not deleted.

This link has a model files example (in case you could give it a try from your side)
[NL-Loo_2024-11-07-1226.zip](https://github.com/user-attachments/files/17749733/NL-Loo_2024-11-07-1226.zip)

**Comment by SarahAlidoost** [comment]
@MostafaGomaa93 The `finalize()` function returns the `ValueError: Model terminated with return code None` because saving CSV files in MATLAB takes longer when dealing with large time series, and this process is slower than the Python process defined [here](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/33adb9e19ecdedfb8446aec5a848374d416d7cfa/PyStemmusScope/bmi/local_process.py#L154-L156). Here are a few ways to fix the issue:
- Remove `io.bin_to_csv()` from the `finalize` block, defined [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/b9b4f8231955589d3394ec5148950467eeaa4ec3/src/STEMMUS_SCOPE.m#L825C5-L825C18): This step is slow when handling longer time series. Instead, the binary-to-CSV conversion should happen after the model finishes, ideally in the [PyStemmusScope.save module](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/33adb9e19ecdedfb8446aec5a848374d416d7cfa/PyStemmusScope/save.py#L243). MATLAB should only save CSV files for debugging purposes.
- Delete unnecessary output files: see [this issue](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/90).
- Increase the sleep function time: It’s currently set to 10 seconds, but this setting can exposed to `StemmusScopeBmi` so users can adjust it. Note that increasing the sleep time will slow down the model runtime overall.

**Comment by SarahAlidoost** [comment]
@MostafaGomaa93 as discussed, beside removing unnecessary output files, the setting can be added to config file. Here  suggestion on how to use an optional variable `SleepDuration` from the config file:
- at [this line](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/33adb9e19ecdedfb8446aec5a848374d416d7cfa/PyStemmusScope/bmi/local_process.py#L89) :
```python
        # set the sleep duration if set in the config file, otherwise default to
        # 10 seconds
        self.sleep_duration = int(config.get("SleepDuration", 10))
```
- and later, it is used in [this line](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/33adb9e19ecdedfb8446aec5a848374d416d7cfa/PyStemmusScope/bmi/local_process.py#L156) as `sleep(self.sleep_duration)`

**Comment by MostafaGomaa93** [comment]
> * Delete unnecessary output files: see [this issue](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/90).

Many thanks, @SarahAlidoost
I removed the unnecessary large files in this [PR](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/273)

**Comment by MostafaGomaa93** [comment]
> * at [this line](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/33adb9e19ecdedfb8446aec5a848374d416d7cfa/PyStemmusScope/bmi/local_process.py#L89) :
> * and later, it is used in [this line](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/33adb9e19ecdedfb8446aec5a848374d416d7cfa/PyStemmusScope/bmi/local_process.py#L156) as `sleep(self.sleep_duration)`

I add those two lines also in this [PR](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/pull/116)
